
###
POST  http://127.0.0.1:8080/api/peppers/create
Content-Type: application/json

{
  "name" : "Kampot IGP noir du Cambodge",
  "type": "BLACK",
  "origin": "Kampot",
  "desc": "Le poivre de Kampot IGP a su faire sa place dans le monde de la gastronomie",
  "kgPrice": 58
}

###

POST  http://127.0.0.1:8080/api/peppers/create
Content-Type: application/json

{
  "name" : "Poivre Cubèbe de Jakarta",
  "type": "BLACK",
  "origin": "Jakarta",
  "desc": "Peu piquant, sa saveur est camphrée, mentholée et citronnée",
  "kgPrice": 59
}

###

PUT  http://127.0.0.1:8080/api/peppers/update/eec4bf80-d708-4c86-a121-b9f11d6582e5
Content-Type: application/json

{
  "name" : "Poivre Cubèbe de Jakarta",
  "type": "BLACK",
  "origin": "Jakarta",
  "desc": "Peu piquant, sa saveur est camphrée, mentholée et citronnée",
  "kgPrice": 59,
  "specifications": [
    "FRUITED",
    "STRONG"
  ]
}

###

GET  http://127.0.0.1:8080/api/peppers/getAll
Content-Type: application/json
Authorization: {{$dotenv APP_ADMIN_SECRET}}

###

GET  http://127.0.0.1:8080/api/peppers/getBySpecification/MILD
Content-Type: application/json

###

DELETE  http://127.0.0.1:8080/api/peppers/deleteByUUid/cd9308ae-b2e8-4d85-b74c-30d51d7b2d1d
Content-Type: application/json

###

DELETE  http://127.0.0.1:8080/api/peppers/deleteByName/courgette
Content-Type: application/json

###

PUT  http://127.0.0.1:8080/api/peppers/validate-pepper/2fbe512f-b070-433a-8ddd-65b83ac70bbd
Content-Type: application/json
Authorization: {{$dotenv APP_ADMIN_SECRET}}

###

GET  http://127.0.0.1:8080/api/peppers/getAllRates
Content-Type: application/json

###

POST  http://127.0.0.1:8080/api/peppers/rate/fd3b2013-abc3-4a75-b7b2-30a771ca98fa
Content-Type: application/json
email: arthur.couturier.2000@gmail.com

5

###
